// <auto-generated />
using System;
using DBNotifier.Persistence.Server.PostgreSql;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DBNotifier.Persistence.Server.PostgreSql.Migrations
{
    [DbContext(typeof(ServerDbContext))]
    [Migration("20260716142357_HardenObservationReconciliation")]
    partial class HardenObservationReconciliation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DBNotifier.Persistence.Server.PostgreSql.AdministrativeCommandRow", b =>
                {
                    b.Property<Guid>("CommandId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("command_id");

                    b.Property<Guid>("AssignedAgentId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_agent_id");

                    b.Property<string>("AuthorizationSnapshotReference")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("authorization_snapshot_reference");

                    b.Property<string>("CapabilityId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("capability_id");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("concurrency_token");

                    b.Property<string>("ExpectedAgentVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("expected_agent_version");

                    b.Property<string>("ExpectedProviderVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("expected_provider_version");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("idempotency_key");

                    b.Property<Guid>("InstanceId")
                        .HasColumnType("uuid")
                        .HasColumnName("instance_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("reason");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_at");

                    b.Property<Guid>("RequestedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("requested_by_user_id");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("state");

                    b.Property<string>("TypedParametersJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("typed_parameters_json");

                    b.HasKey("CommandId");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("RequestedByUserId");

                    b.HasIndex("InstanceId", "RequestedAt");

                    b.HasIndex("AssignedAgentId", "State", "ExpiresAt");

                    b.ToTable("administrative_commands", null, t =>
                        {
                            t.HasCheckConstraint("ck_command_expiry", "expires_at > requested_at");

                            t.HasCheckConstraint("ck_command_state", "state IN ('Pending','Available','Acknowledged','Running','Succeeded','Failed','Cancelled','Expired','Rejected','UnknownOutcome')");
                        });
                });

            modelBuilder.Entity("DBNotifier.Persistence.Server.PostgreSql.AgentCapabilityRow", b =>
                {
                    b.Property<Guid>("AgentCapabilityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("agent_capability_id");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("uuid")
                        .HasColumnName("agent_id");

                    b.Property<string>("CapabilityId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("capability_id");

                    b.Property<DateTimeOffset>("ObservedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("observed_at");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("platform");

                    b.Property<string>("ProviderType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("provider_type");

                    b.Property<string>("ProviderVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("provider_version");

                    b.Property<string>("ReasonCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("reason_code");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("state");

                    b.HasKey("AgentCapabilityId");

                    b.HasIndex("AgentId", "CapabilityId", "ProviderType", "ProviderVersion", "Platform")
                        .IsUnique();

                    b.ToTable("agent_capabilities", null, t =>
                        {
                            t.HasCheckConstraint("ck_agent_capability_state", "state IN ('Supported','Unsupported','Unavailable','Unknown')");
                        });
                });

            modelBuilder.Entity("DBNotifier.Persistence.Server.PostgreSql.AgentHeartbeatRow", b =>
                {
                    b.Property<Guid>("HeartbeatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("heartbeat_id");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("uuid")
                        .HasColumnName("agent_id");

                    b.Property<DateTimeOffset>("AgentTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("agent_time");

                    b.Property<string>("AgentVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("agent_version");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<DateTimeOffset?>("OldestQueuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("oldest_queued_at");

                    b.Property<int>("ProtocolMaximum")
                        .HasColumnType("integer")
                        .HasColumnName("protocol_maximum");

                    b.Property<int>("ProtocolMinimum")
                        .HasColumnType("integer")
                        .HasColumnName("protocol_minimum");

                    b.Property<long>("QueueDepth")
                        .HasColumnType("bigint")
                        .HasColumnName("queue_depth");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<long>("Sequence")
                        .HasColumnType("bigint")
                        .HasColumnName("sequence");

                    b.HasKey("HeartbeatId");

                    b.HasIndex("MessageId")
                        .IsUnique();

                    b.HasIndex("AgentId", "ReceivedAt");

                    b.ToTable("agent_heartbeats", null, t =>
                        {
                            t.HasCheckConstraint("ck_heartbeat_protocol", "protocol_minimum >= 1 AND protocol_maximum >= protocol_minimum");

                            t.HasCheckConstraint("ck_heartbeat_queue", "queue_depth >= 0");

                            t.HasCheckConstraint("ck_heartbeat_sequence", "sequence >= 0");
                        });
                });

            modelBuilder.Entity("DBNotifier.Persistence.Server.PostgreSql.AgentObservationCursorRow", b =>
                {
                    b.Property<Guid>("AgentId")
                        .HasColumnType("uuid")
                        .HasColumnName("agent_id");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("concurrency_token");

                    b.Property<long>("HighestContiguousSequence")
                        .HasColumnType("bigint")
                        .HasColumnName("highest_contiguous_sequence");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("AgentId");

                    b.ToTable("agent_observation_cursors", null, t =>
                        {
                            t.HasCheckConstraint("ck_agent_observation_cursor_sequence", "highest_contiguous_sequence >= 0");
                        });
                });

            modelBuilder.Entity("DBNotifier.Persistence.Server.PostgreSql.AlertRuleRow", b =>
                {
                    b.Property<Guid>("AlertRuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("alert_rule_id");

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("concurrency_token");

                    b.Property<string>("ConfigurationJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("configuration_json");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<string>("InstanceScopeJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("instance_scope_json");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("RuleType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("rule_type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("AlertRuleId");

                    b.HasIndex("Enabled", "RuleType");

                    b.ToTable("alert_rules", (string)null);
                });

            modelBuilder.Entity("DBNotifier.Persistence.Server.PostgreSql.AuditEntryRow", b =>
                {
                    b.Property<Guid>("AuditEntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("audit_entry_id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("action");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("actor_id");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("actor_type");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<string>("DetailsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("details_json");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("outcome");

                    b.Property<string>("TargetId")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("target_id");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("target_type");

                    b.HasKey("AuditEntryId");

                    b.HasIndex("CorrelationId");

                    b.HasIndex("OccurredAt");

                    b.HasIndex("ActorType", "ActorId", "OccurredAt");

                    b.ToTable("audit_entries", null, t =>
                        {
                            t.HasCheckConstraint("ck_audit_outcome", "outcome IN ('Succeeded','Failed','Denied','Unknown')");
                        });
                });

            modelBuilder.Entity("DBNotifier.Persistence.Server.PostgreSql.CommandAttemptRow", b =>
                {
                    b.Property<Guid>("CommandAttemptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("command_attempt_id");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_number");

                    b.Property<Guid>("CommandId")
                        .HasColumnType("uuid")
                        .HasColumnName("command_id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("DiagnosticReference")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("diagnostic_reference");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("error_code");

                    b.Property<Guid?>("PostProbeObservationId")
                        .HasColumnType("uuid")
                        .HasColumnName("post_probe_observation_id");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("state");

                    b.HasKey("CommandAttemptId");

                    b.HasIndex("PostProbeObservationId");

                    b.HasIndex("CommandId", "AttemptNumber")
                        .IsUnique();

                    b.ToTable("command_attempts", null, t =>
                        {
                            t.HasCheckConstraint("ck_command_attempt_number", "attempt_number >= 1");

                            t.HasCheckConstraint("ck_command_attempt_state", "state IN ('Running','Succeeded','Failed','Cancelled','Expired','Rejected','UnknownOutcome')");
                        });
                });

            modelBuilder.Entity("DBNotifier.Persistence.Server.PostgreSql.DatabaseInstanceRow", b =>
                {
                    b.Property<Guid>("InstanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("instance_id");

                    b.Property<string>("AdministrativeCredentialReference")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("administrative_credential_reference");

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at");

                    b.Property<Guid?>("AssignedAgentId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_agent_id");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("concurrency_token");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<string>("EndpointJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("endpoint_json");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("environment");

                    b.Property<int>("IntervalSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("interval_seconds");

                    b.Property<string>("MonitoringCredentialReference")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("monitoring_credential_reference");

                    b.Property<string>("ProviderType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("provider_type");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.Property<string>("TagsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("tags_json");

                    b.Property<int>("TimeoutSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("timeout_seconds");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("InstanceId");

                    b.HasIndex("AssignedAgentId");

                    b.HasIndex("Environment", "ProviderType", "Enabled");

                    b.ToTable("database_instances", null, t =>
                        {
                            t.HasCheckConstraint("ck_instance_interval", "interval_seconds >= 1");

                            t.HasCheckConstraint("ck_instance_retries", "retry_count >= 0");

                            t.HasCheckConstraint("ck_instance_timeout", "timeout_seconds >= 1");
                        });
                });

            modelBuilder.Entity("DBNotifier.Persistence.Server.PostgreSql.EventRecordRow", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<Guid?>("AgentId")
                        .HasColumnType("uuid")
                        .HasColumnName("agent_id");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<string>("DetailsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("details_json");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("event_type");

                    b.Property<Guid?>("InstanceId")
                        .HasColumnType("uuid")
                        .HasColumnName("instance_id");

                    b.Property<DateTimeOffset>("ObservedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("observed_at");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("severity");

                    b.Property<Guid?>("SourceObservationId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_observation_id");

                    b.HasKey("EventId");

                    b.HasIndex("AgentId");

                    b.HasIndex("CorrelationId");

                    b.HasIndex("SourceObservationId");

                    b.HasIndex("EventType", "ObservedAt");

                    b.HasIndex("InstanceId", "ObservedAt");

                    b.ToTable("events", null, t =>
                        {
                            t.HasCheckConstraint("ck_event_severity", "severity IN ('Info','Warning','Error','Critical')");
                        });
                });

            modelBuilder.Entity("DBNotifier.Persistence.Server.PostgreSql.HealthSampleRow", b =>
                {
                    b.Property<Guid>("ObservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("observation_id");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("uuid")
                        .HasColumnName("agent_id");

                    b.Property<int>("AttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("attempt_count");

                    b.Property<long>("DurationMilliseconds")
                        .HasColumnType("bigint")
                        .HasColumnName("duration_milliseconds");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("error_code");

                    b.Property<string>("EvidenceLevel")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("evidence_level");

                    b.Property<Guid>("InstanceId")
                        .HasColumnType("uuid")
                        .HasColumnName("instance_id");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("method");

                    b.Property<DateTimeOffset>("ObservedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("observed_at");

                    b.Property<string>("PayloadHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("payload_hash");

                    b.Property<string>("ProviderType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("provider_type");

                    b.Property<string>("ProviderVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("provider_version");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<string>("RedactedDetailsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("redacted_details_json");

                    b.Property<long>("Sequence")
                        .HasColumnType("bigint")
                        .HasColumnName("sequence");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.HasKey("ObservationId");

                    b.HasIndex("MessageId")
                        .IsUnique();

                    b.HasIndex("AgentId", "Sequence")
                        .IsUnique();

                    b.HasIndex("InstanceId", "ObservedAt");

                    b.HasIndex("Status", "ObservedAt");

                    b.ToTable("health_samples", null, t =>
                        {
                            t.HasCheckConstraint("ck_health_attempts", "attempt_count >= 1");

                            t.HasCheckConstraint("ck_health_duration", "duration_milliseconds >= 0");

                            t.HasCheckConstraint("ck_health_evidence", "evidence_level IN ('ProviderAuthenticated','ProviderReadiness','TransportOnly','Synthetic','Unknown')");

                            t.HasCheckConstraint("ck_health_status", "status IN ('Healthy','Degraded','Unavailable','AuthFailed','Timeout','Maintenance','Unknown')");
                        });
                });

            modelBuilder.Entity("DBNotifier.Persistence.Server.PostgreSql.IncidentRow", b =>
                {
                    b.Property<Guid>("IncidentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("incident_id");

                    b.Property<DateTimeOffset?>("AcknowledgedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("acknowledged_at");

                    b.Property<Guid?>("AcknowledgedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("acknowledged_by_user_id");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<Guid?>("ClosedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("closed_by_user_id");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("concurrency_token");

                    b.Property<Guid>("InstanceId")
                        .HasColumnType("uuid")
                        .HasColumnName("instance_id");

                    b.Property<DateTimeOffset>("OpenedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("opened_at");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("severity");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.HasKey("IncidentId");

                    b.HasIndex("OpenedAt");

                    b.HasIndex("InstanceId", "Status");

                    b.ToTable("incidents", null, t =>
                        {
                            t.HasCheckConstraint("ck_incident_severity", "severity IN ('Info','Warning','Error','Critical')");

                            t.HasCheckConstraint("ck_incident_state", "status IN ('Open','Acknowledged','Closed')");
                        });
                });

            modelBuilder.Entity("DBNotifier.Persistence.Server.PostgreSql.InstanceObservationStateRow", b =>
                {
                    b.Property<Guid>("InstanceId")
                        .HasColumnType("uuid")
                        .HasColumnName("instance_id");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("uuid")
                        .HasColumnName("agent_id");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("concurrency_token");

                    b.Property<long>("LastProcessedSequence")
                        .HasColumnType("bigint")
                        .HasColumnName("last_processed_sequence");

                    b.Property<Guid>("ObservationId")
                        .HasColumnType("uuid")
                        .HasColumnName("observation_id");

                    b.Property<DateTimeOffset>("ObservedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("observed_at");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.HasKey("InstanceId");

                    b.HasIndex("AgentId", "LastProcessedSequence");

                    b.ToTable("instance_observation_states", null, t =>
                        {
                            t.HasCheckConstraint("ck_instance_observation_state_sequence", "last_processed_sequence >= 1");

                            t.HasCheckConstraint("ck_instance_observation_state_status", "status IN ('Healthy','Degraded','Unavailable','AuthFailed','Timeout','Maintenance','Unknown')");
                        });
                });

            modelBuilder.Entity("DBNotifier.Persistence.Server.PostgreSql.MaintenanceWindowRow", b =>
                {
                    b.Property<Guid>("MaintenanceWindowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("maintenance_window_id");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("concurrency_token");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTimeOffset>("EndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ends_at");

                    b.Property<Guid>("InstanceId")
                        .HasColumnType("uuid")
                        .HasColumnName("instance_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("reason");

                    b.Property<DateTimeOffset>("StartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at");

                    b.HasKey("MaintenanceWindowId");

                    b.HasIndex("InstanceId", "StartsAt", "EndsAt");

                    b.ToTable("maintenance_windows", null, t =>
                        {
                            t.HasCheckConstraint("ck_maintenance_range", "ends_at > starts_at");
                        });
                });

            modelBuilder.Entity("DBNotifier.Persistence.Server.PostgreSql.NotificationChannelRow", b =>
                {
                    b.Property<Guid>("NotificationChannelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("notification_channel_id");

                    b.Property<string>("ChannelType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("channel_type");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("concurrency_token");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CredentialReference")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("credential_reference");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("NonSecretConfigurationJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("non_secret_configuration_json");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("NotificationChannelId");

                    b.HasIndex("ChannelType", "Enabled");

                    b.ToTable("notification_channels", (string)null);
                });

            modelBuilder.Entity("DBNotifier.Persistence.Server.PostgreSql.NotificationDeliveryRow", b =>
                {
                    b.Property<Guid>("NotificationDeliveryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("notification_delivery_id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivered_at");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("error_code");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<DateTimeOffset?>("LastAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_attempt_at");

                    b.Property<Guid>("NotificationChannelId")
                        .HasColumnType("uuid")
                        .HasColumnName("notification_channel_id");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("state");

                    b.HasKey("NotificationDeliveryId");

                    b.HasIndex("EventId");

                    b.HasIndex("NotificationChannelId", "EventId")
                        .IsUnique();

                    b.HasIndex("State", "CreatedAt");

                    b.ToTable("notification_deliveries", null, t =>
                        {
                            t.HasCheckConstraint("ck_delivery_attempts", "attempt_count >= 0");

                            t.HasCheckConstraint("ck_delivery_state", "state IN ('Pending','Delivering','Delivered','Failed','Cancelled')");
                        });
                });

            modelBuilder.Entity("DBNotifier.Persistence.Server.PostgreSql.PermissionRow", b =>
                {
                    b.Property<Guid>("PermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("permission_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.HasKey("PermissionId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("permissions", (string)null);
                });

            modelBuilder.Entity("DBNotifier.Persistence.Server.PostgreSql.PlatformUserRow", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("concurrency_token");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("state");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("subject_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("UserId");

                    b.HasIndex("SubjectId")
                        .IsUnique();

                    b.ToTable("users", null, t =>
                        {
                            t.HasCheckConstraint("ck_user_state", "state IN ('Active','Disabled','Locked','Unknown')");
                        });
                });

            modelBuilder.Entity("DBNotifier.Persistence.Server.PostgreSql.RegisteredAgentRow", b =>
                {
                    b.Property<Guid>("AgentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("agent_id");

                    b.Property<string>("AgentVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("agent_version");

                    b.Property<string>("CertificateThumbprint")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("certificate_thumbprint");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("concurrency_token");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<DateTimeOffset>("EnrolledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("enrolled_at");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("environment");

                    b.Property<string>("InstallationId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("installation_id");

                    b.Property<DateTimeOffset?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("platform");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("state");

                    b.HasKey("AgentId");

                    b.HasIndex("CertificateThumbprint")
                        .IsUnique();

                    b.HasIndex("InstallationId")
                        .IsUnique();

                    b.HasIndex("Environment", "State");

                    b.ToTable("agents", null, t =>
                        {
                            t.HasCheckConstraint("ck_agent_state", "state IN ('Active','Revoked','Disabled','Unknown')");
                        });
                });

            modelBuilder.Entity("DBNotifier.Persistence.Server.PostgreSql.RoleAssignmentRow", b =>
                {
                    b.Property<Guid>("RoleAssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("role_assignment_id");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset>("GrantedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("granted_at");

                    b.Property<Guid>("GrantedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("granted_by_user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<string>("ScopeType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("scope_type");

                    b.Property<string>("ScopeValue")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("scope_value");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("RoleAssignmentId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId", "RoleId", "ScopeType", "ScopeValue")
                        .IsUnique();

                    b.ToTable("role_assignments", (string)null);
                });

            modelBuilder.Entity("DBNotifier.Persistence.Server.PostgreSql.RolePermissionRow", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("permission_id");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("role_permissions", (string)null);
                });

            modelBuilder.Entity("DBNotifier.Persistence.Server.PostgreSql.RoleRow", b =>
                {
                    b.Property<Guid>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("concurrency_token");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean")
                        .HasColumnName("is_system");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("RoleId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("DBNotifier.Persistence.Server.PostgreSql.ServerOutboxMessageRow", b =>
                {
                    b.Property<Guid>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<DateTimeOffset>("AvailableAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("available_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("message_type");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_json");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("integer")
                        .HasColumnName("schema_version");

                    b.HasKey("MessageId");

                    b.HasIndex("PublishedAt", "AvailableAt");

                    b.ToTable("outbox_messages", null, t =>
                        {
                            t.HasCheckConstraint("ck_server_outbox_attempts", "attempt_count >= 0");

                            t.HasCheckConstraint("ck_server_outbox_schema", "schema_version >= 1");
                        });
                });

            modelBuilder.Entity("DBNotifier.Persistence.Server.PostgreSql.AdministrativeCommandRow", b =>
                {
                    b.HasOne("DBNotifier.Persistence.Server.PostgreSql.RegisteredAgentRow", null)
                        .WithMany()
                        .HasForeignKey("AssignedAgentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DBNotifier.Persistence.Server.PostgreSql.DatabaseInstanceRow", null)
                        .WithMany()
                        .HasForeignKey("InstanceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DBNotifier.Persistence.Server.PostgreSql.PlatformUserRow", null)
                        .WithMany()
                        .HasForeignKey("RequestedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DBNotifier.Persistence.Server.PostgreSql.AgentCapabilityRow", b =>
                {
                    b.HasOne("DBNotifier.Persistence.Server.PostgreSql.RegisteredAgentRow", null)
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DBNotifier.Persistence.Server.PostgreSql.AgentHeartbeatRow", b =>
                {
                    b.HasOne("DBNotifier.Persistence.Server.PostgreSql.RegisteredAgentRow", null)
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DBNotifier.Persistence.Server.PostgreSql.AgentObservationCursorRow", b =>
                {
                    b.HasOne("DBNotifier.Persistence.Server.PostgreSql.RegisteredAgentRow", null)
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DBNotifier.Persistence.Server.PostgreSql.CommandAttemptRow", b =>
                {
                    b.HasOne("DBNotifier.Persistence.Server.PostgreSql.AdministrativeCommandRow", null)
                        .WithMany()
                        .HasForeignKey("CommandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DBNotifier.Persistence.Server.PostgreSql.HealthSampleRow", null)
                        .WithMany()
                        .HasForeignKey("PostProbeObservationId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("DBNotifier.Persistence.Server.PostgreSql.DatabaseInstanceRow", b =>
                {
                    b.HasOne("DBNotifier.Persistence.Server.PostgreSql.RegisteredAgentRow", null)
                        .WithMany()
                        .HasForeignKey("AssignedAgentId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("DBNotifier.Persistence.Server.PostgreSql.EventRecordRow", b =>
                {
                    b.HasOne("DBNotifier.Persistence.Server.PostgreSql.RegisteredAgentRow", null)
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DBNotifier.Persistence.Server.PostgreSql.DatabaseInstanceRow", null)
                        .WithMany()
                        .HasForeignKey("InstanceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DBNotifier.Persistence.Server.PostgreSql.HealthSampleRow", null)
                        .WithMany()
                        .HasForeignKey("SourceObservationId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("DBNotifier.Persistence.Server.PostgreSql.HealthSampleRow", b =>
                {
                    b.HasOne("DBNotifier.Persistence.Server.PostgreSql.RegisteredAgentRow", null)
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DBNotifier.Persistence.Server.PostgreSql.DatabaseInstanceRow", null)
                        .WithMany()
                        .HasForeignKey("InstanceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DBNotifier.Persistence.Server.PostgreSql.IncidentRow", b =>
                {
                    b.HasOne("DBNotifier.Persistence.Server.PostgreSql.DatabaseInstanceRow", null)
                        .WithMany()
                        .HasForeignKey("InstanceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DBNotifier.Persistence.Server.PostgreSql.InstanceObservationStateRow", b =>
                {
                    b.HasOne("DBNotifier.Persistence.Server.PostgreSql.RegisteredAgentRow", null)
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DBNotifier.Persistence.Server.PostgreSql.DatabaseInstanceRow", null)
                        .WithMany()
                        .HasForeignKey("InstanceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DBNotifier.Persistence.Server.PostgreSql.MaintenanceWindowRow", b =>
                {
                    b.HasOne("DBNotifier.Persistence.Server.PostgreSql.DatabaseInstanceRow", null)
                        .WithMany()
                        .HasForeignKey("InstanceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DBNotifier.Persistence.Server.PostgreSql.NotificationDeliveryRow", b =>
                {
                    b.HasOne("DBNotifier.Persistence.Server.PostgreSql.EventRecordRow", null)
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DBNotifier.Persistence.Server.PostgreSql.NotificationChannelRow", null)
                        .WithMany()
                        .HasForeignKey("NotificationChannelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DBNotifier.Persistence.Server.PostgreSql.RoleAssignmentRow", b =>
                {
                    b.HasOne("DBNotifier.Persistence.Server.PostgreSql.RoleRow", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DBNotifier.Persistence.Server.PostgreSql.PlatformUserRow", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DBNotifier.Persistence.Server.PostgreSql.RolePermissionRow", b =>
                {
                    b.HasOne("DBNotifier.Persistence.Server.PostgreSql.PermissionRow", null)
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DBNotifier.Persistence.Server.PostgreSql.RoleRow", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
