// <auto-generated />
using System;
using DBNotifier.Persistence.Agent.Sqlite;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DBNotifier.Persistence.Agent.Sqlite.Migrations
{
    [DbContext(typeof(AgentDbContext))]
    [Migration("20260718035633_IntegrateAgentFleetClientState")]
    partial class IntegrateAgentFleetClientState
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("DBNotifier.Persistence.Agent.Sqlite.AgentCheckpointRow", b =>
                {
                    b.Property<string>("StreamName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("stream_name");

                    b.Property<long>("Sequence")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sequence");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("StreamName");

                    b.ToTable("checkpoints", null, t =>
                        {
                            t.HasCheckConstraint("ck_checkpoint_sequence", "sequence >= 0");
                        });
                });

            modelBuilder.Entity("DBNotifier.Persistence.Agent.Sqlite.AgentFleetStateRow", b =>
                {
                    b.Property<Guid>("AgentId")
                        .HasColumnType("TEXT")
                        .HasColumnName("agent_id");

                    b.Property<string>("AssignmentEntityTag")
                        .HasMaxLength(66)
                        .HasColumnType("TEXT")
                        .HasColumnName("assignment_entity_tag");

                    b.Property<DateTimeOffset?>("AssignmentGeneratedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("assignment_generated_at");

                    b.Property<DateTimeOffset?>("AssignmentLastSucceededAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("assignment_last_succeeded_at");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT")
                        .HasColumnName("concurrency_token");

                    b.Property<DateTimeOffset?>("LastAttemptAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_attempt_at");

                    b.Property<string>("LastErrorCode")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("last_error_code");

                    b.Property<DateTimeOffset?>("LastHeartbeatAcceptedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_heartbeat_accepted_at");

                    b.Property<long>("NextHeartbeatSequence")
                        .HasColumnType("INTEGER")
                        .HasColumnName("next_heartbeat_sequence");

                    b.Property<Guid?>("PendingHeartbeatMessageId")
                        .HasColumnType("TEXT")
                        .HasColumnName("pending_heartbeat_message_id");

                    b.Property<string>("PendingHeartbeatPayloadJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("pending_heartbeat_payload_json");

                    b.Property<long?>("PendingHeartbeatSequence")
                        .HasColumnType("INTEGER")
                        .HasColumnName("pending_heartbeat_sequence");

                    b.HasKey("AgentId");

                    b.ToTable("agent_fleet_state", null, t =>
                        {
                            t.HasCheckConstraint("ck_agent_fleet_next_heartbeat", "next_heartbeat_sequence >= 1");

                            t.HasCheckConstraint("ck_agent_fleet_pending_heartbeat", "(pending_heartbeat_message_id IS NULL AND pending_heartbeat_sequence IS NULL AND pending_heartbeat_payload_json IS NULL) OR (pending_heartbeat_message_id IS NOT NULL AND pending_heartbeat_sequence >= 1 AND pending_heartbeat_payload_json IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("DBNotifier.Persistence.Agent.Sqlite.AgentHealthObservationRow", b =>
                {
                    b.Property<Guid>("ObservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("observation_id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("attempt_count");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<long>("DurationMilliseconds")
                        .HasColumnType("INTEGER")
                        .HasColumnName("duration_milliseconds");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("error_code");

                    b.Property<string>("EvidenceLevel")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("evidence_level");

                    b.Property<Guid>("InstanceId")
                        .HasColumnType("TEXT")
                        .HasColumnName("instance_id");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("method");

                    b.Property<DateTimeOffset>("ObservedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("observed_at");

                    b.Property<string>("ProviderType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("provider_type");

                    b.Property<string>("ProviderVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("provider_version");

                    b.Property<string>("RedactedDetailsJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("redacted_details_json");

                    b.Property<string>("SafeErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("safe_error_message");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.HasKey("ObservationId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("InstanceId", "ObservedAt");

                    b.ToTable("health_observations", null, t =>
                        {
                            t.HasCheckConstraint("ck_agent_health_attempts", "attempt_count >= 1");

                            t.HasCheckConstraint("ck_agent_health_duration", "duration_milliseconds >= 0");

                            t.HasCheckConstraint("ck_agent_health_status", "status IN ('Healthy','Degraded','Unavailable','AuthFailed','Timeout','Maintenance','Unknown')");
                        });
                });

            modelBuilder.Entity("DBNotifier.Persistence.Agent.Sqlite.AgentInboxCommandRow", b =>
                {
                    b.Property<Guid>("CommandId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("command_id");

                    b.Property<DateTimeOffset?>("AcknowledgedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("acknowledged_at");

                    b.Property<string>("CapabilityId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("capability_id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("completed_at");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT")
                        .HasColumnName("concurrency_token");

                    b.Property<string>("ExpectedAgentVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("expected_agent_version");

                    b.Property<string>("ExpectedProviderVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("expected_provider_version");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("expires_at");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("idempotency_key");

                    b.Property<Guid>("InstanceId")
                        .HasColumnType("TEXT")
                        .HasColumnName("instance_id");

                    b.Property<string>("ProviderId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("provider_id");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("requested_at");

                    b.Property<string>("ResultJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("result_json");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("state");

                    b.Property<string>("TypedParametersJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("typed_parameters_json");

                    b.HasKey("CommandId");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("State", "ExpiresAt");

                    b.ToTable("inbox_commands", null, t =>
                        {
                            t.HasCheckConstraint("ck_agent_command_state", "state IN ('Pending','Available','Acknowledged','Running','Succeeded','Failed','Cancelled','Expired','Rejected','UnknownOutcome')");
                        });
                });

            modelBuilder.Entity("DBNotifier.Persistence.Agent.Sqlite.AgentInstanceAssignmentRow", b =>
                {
                    b.Property<Guid>("InstanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("instance_id");

                    b.Property<string>("AdministrativeCredentialReference")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("administrative_credential_reference");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT")
                        .HasColumnName("concurrency_token");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("display_name");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("enabled");

                    b.Property<string>("EndpointJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("endpoint_json");

                    b.Property<int>("IntervalSeconds")
                        .HasColumnType("INTEGER")
                        .HasColumnName("interval_seconds");

                    b.Property<string>("MonitoringCredentialReference")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("monitoring_credential_reference");

                    b.Property<string>("PolicyVersion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("policy_version");

                    b.Property<string>("ProviderType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("provider_type");

                    b.Property<int>("RetryCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("retry_count");

                    b.Property<string>("TagsJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("tags_json");

                    b.Property<int>("TimeoutSeconds")
                        .HasColumnType("INTEGER")
                        .HasColumnName("timeout_seconds");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("InstanceId");

                    b.HasIndex("ProviderType", "Enabled");

                    b.ToTable("instance_assignments", null, t =>
                        {
                            t.HasCheckConstraint("ck_instance_assignment_interval", "interval_seconds >= 1");

                            t.HasCheckConstraint("ck_instance_assignment_retries", "retry_count >= 0");

                            t.HasCheckConstraint("ck_instance_assignment_timeout", "timeout_seconds >= 1");
                        });
                });

            modelBuilder.Entity("DBNotifier.Persistence.Agent.Sqlite.AgentOutboxMessageRow", b =>
                {
                    b.Property<Guid>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("message_id");

                    b.Property<DateTimeOffset?>("AcknowledgedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("acknowledged_at");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("attempt_count");

                    b.Property<DateTimeOffset>("AvailableAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("available_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("message_type");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("occurred_at");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("payload_json");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("INTEGER")
                        .HasColumnName("schema_version");

                    b.Property<long>("Sequence")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sequence");

                    b.HasKey("MessageId");

                    b.HasIndex("Sequence")
                        .IsUnique();

                    b.HasIndex("AcknowledgedAt", "AvailableAt");

                    b.ToTable("outbox_messages", null, t =>
                        {
                            t.HasCheckConstraint("ck_agent_outbox_attempts", "attempt_count >= 0");

                            t.HasCheckConstraint("ck_agent_outbox_schema", "schema_version >= 1");

                            t.HasCheckConstraint("ck_agent_outbox_sequence", "sequence >= 0");
                        });
                });

            modelBuilder.Entity("DBNotifier.Persistence.Agent.Sqlite.AgentRegistrationRow", b =>
                {
                    b.Property<Guid>("AgentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("agent_id");

                    b.Property<string>("ActiveConfigurationVersion")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("active_configuration_version");

                    b.Property<DateTimeOffset>("CertificateNotAfter")
                        .HasColumnType("TEXT")
                        .HasColumnName("certificate_not_after");

                    b.Property<string>("CertificateThumbprint")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT")
                        .HasColumnName("certificate_thumbprint");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT")
                        .HasColumnName("concurrency_token");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("environment");

                    b.Property<string>("IdentityCertificateReference")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("identity_certificate_reference");

                    b.Property<string>("IdentityState")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("identity_state");

                    b.Property<string>("InstallationId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT")
                        .HasColumnName("installation_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("AgentId");

                    b.HasIndex("InstallationId")
                        .IsUnique();

                    b.ToTable("agent_registration", null, t =>
                        {
                            t.HasCheckConstraint("ck_agent_registration_identity_state", "identity_state IN ('NotEnrolled','Active','Offline','Stale','Incompatible','Expired','RevokedOrDenied','Conflict')");
                        });
                });

            modelBuilder.Entity("DBNotifier.Persistence.Agent.Sqlite.AgentFleetStateRow", b =>
                {
                    b.HasOne("DBNotifier.Persistence.Agent.Sqlite.AgentRegistrationRow", null)
                        .WithOne()
                        .HasForeignKey("DBNotifier.Persistence.Agent.Sqlite.AgentFleetStateRow", "AgentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
