<!-- Module purpose: Defines .NET 10 build settings and dependencies for DBNotifier Agent Worker. -->
<Project Sdk="Microsoft.NET.Sdk.Worker">
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
    <ProjectReference Include="..\DBNotifier.Application\DBNotifier.Application.csproj" />
    <ProjectReference Include="..\DBNotifier.Infrastructure\DBNotifier.Infrastructure.csproj" />
    <ProjectReference Include="..\DBNotifier.Persistence.Agent.Sqlite\DBNotifier.Persistence.Agent.Sqlite.csproj" />
    <ProjectReference Include="..\DBNotifier.Providers.PostgreSql\DBNotifier.Providers.PostgreSql.csproj" />
  </ItemGroup>
</Project>
