<!-- Module purpose: Defines .NET 10 build settings and dependencies for DBNotifier Application. -->
<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\DBNotifier.Domain\DBNotifier.Domain.csproj" />
    <ProjectReference Include="..\DBNotifier.Provider.Abstractions\DBNotifier.Provider.Abstractions.csproj" />
  </ItemGroup>
</Project>
