<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />
    <ProjectReference Include="..\DBNotifier.Application\DBNotifier.Application.csproj" />
    <ProjectReference Include="..\DBNotifier.Domain\DBNotifier.Domain.csproj" />
  </ItemGroup>
</Project>
